using System;
using ExerciciosComCsharp;
using ExerciciosComCsharp.DatasETempo;
using ExerciciosComCsharp.EstruturasDeControle;
using ExerciciosComCsharp.EstruturasDeControle.CondicionalIfElse.CondicionalIfElseSimples;
using ExerciciosComCsharp.EstruturasDeControle.While;
using ExerciciosComCsharp.ExerciciosComMetodos;
using ExerciciosComCsharp.ManipulacaoDenNumeros;
using ExerciciosComCsharp.OperacoesMatematicas.Calculos;
using ExerciciosComCsharp.OperacoesMatematicas.Conversoes;
using ExerciciosComCsharp.OperacoesMatematicas.Geometria;
using ExerciciosComCsharp.OperacoesMatematicas.NumerosEBasicos;
using ExerciciosComCsharp.OperacoesMatematicas.Porcentagens;
using ExerciciosComCsharp.OrientacaoAObjetos;
using ExerciciosComCsharp.VetoresEArrays;

Senha.Main(args);
