using System;
using ExerciciosComCsharp;
using ExerciciosComCsharp.DatasETempo;
using ExerciciosComCsharp.EstruturasDeControle;
using ExerciciosComCsharp.EstruturasDeControle.CondicionalIfElse;
using ExerciciosComCsharp.EstruturasDeControle.While;
using ExerciciosComCsharp.ExerciciosComMetodos;
using ExerciciosComCsharp.ManipulacaoDenNumeros;
using ExerciciosComCsharp.OperacoesMatematicas.Conversoes;
using ExerciciosComCsharp.OperacoesMatematicas.Geometria;
using ExerciciosComCsharp.OperacoesMatematicas.NumerosEBasicos;
using ExerciciosComCsharp.OperacoesMatematicas.Porcentagens;
using ExerciciosComCsharp.OrientacaoAObjetos;
using ExerciciosComCsharp.ProgramacaoOrientadaAObjetos.Construtores;
using ExerciciosComCsharp.ProgramacaoOrientadaAObjetos.Propriedades;
using ExerciciosComCsharp.VetoresEArrays;

ValorCarro.Main(args);
